name: Assign Issue to Creator

on:
  issues:
    types:
      - opened

jobs:
  assign-to-creator:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Issue to Creator
        uses: peter-evans/create-or-update-issue@v2
        with:
          issue: ${{ github.event.issue.number }}
          assignees: ${{ github.event.issue.user.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.SNOW }}
